config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"
  get '/components', to: 'components#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/dashboard', to: 'pages#dashboard', as: :dashboard

  get '/users/:user_id/chat', to: 'chatrooms#new_chatroom_with_user', as: 'new_chatroom_with_user'


  resources :activities do
    collection do
      get :map
    end
    resources :bookings, :comments, only: [:create, :destroy]
  end

  resources :bookings, only: :destroy do
    member do
      get :confirmation
    end
  end

  resources :users, only: :show

  resources :chatrooms, only: [:new,:show, :index, :create] do
    resources :messages, only: :create
  end
end

# Path: app/controllers/pages_controller.rb

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :organized_activities, class_name: "Activity", foreign_key: :user_id
  has_many :bookings, dependent: :destroy
  has_many :attending_activities, through: :bookings, source: :activity
  validates :name, presence: true
  validates :bio, presence: true
  validates :age, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 18 }
  validates :photo, presence: true
  # has_many :chatrooms
  has_many :chatrooms_as_recipient, class_name: "Chatroom", foreign_key: :recipient_id
  has_many :comments, dependent: :destroy

  def chatrooms
    Chatroom.where(user_id: id).or(Chatroom.where(recipient_id: id))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @attending_activities = @user.attending_activities
    @organized_activities = @user.organized_activities
  end

  def create
  end
end

app/views/users/show.html.erb
<div id="users-show">
  <div class="card-profile">
     
    <% if user_signed_in? %>
      <div class="logout">
        <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
          <i class="fa-solid fa-power-off"></i>
        <% end %>
      </div>
    <% end %>
    <%= cl_image_tag @user.photo.key, class: "card-profile-picture" %>
    <h1 class="name-age"><%= @user.name%>, <%= @user.age%></h1>
    <p class="about-me">About me</p>
    <%= @user.bio%>
    <% if user_signed_in? && current_user == @user %>
      <%= link_to edit_user_registration_path, class: "button-edit" do %>
          <i class="fa-regular fa-pen-to-square"></i> Edit Profile
      <% end %>
    <% else %>
      <%= link_to new_chatroom_with_user_path(user_id: @user.id), class: "button-edit" do %>
          <i class="fa-brands fa-rocketchat"></i>
      <% end %>
    <% end %>
  </div>
  <div class="my-class">
    <% if @user.organized_activities.present? %>
      <p class="organizing">Organizing</p>
      <% @user.organized_activities.order(:time).each do |activity| %>
        <%= link_to activity_path(activity) do %>
          <div class="card-event">
            <%= cl_image_tag activity.photos.first.key, class: "picture-profile-card" %>
            <div class="infos-activity">
              <h3 class="infos"><%= activity.title %></h3>
              <p class="time"><%= activity.time.strftime('%b %d, %Y at %H:%M') %></p>
              <p class="location"><i class="fa-solid fa-location-dot"></i> <%= activity.location %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <h3>You have no organized activities</h3>
    <% end %>
    <% if @user.attending_activities.present? %>
      <p class="going-to">Going to</p>
      <% @user.attending_activities.order(:time).each do |activity| %>
        <%= link_to activity_path(activity) do %>
          <div class="card-event">
            <%= cl_image_tag activity.photos.first.key, class: "picture-profile-card" %>
            <div class="infos-activity">
              <h3 class="infos"><%= activity.title %></h3>
              <p class="time"><%= activity.time.strftime('%b %d, %Y at %H:%M') %></p>
              <p class="location"><i class="fa-solid fa-location-dot"></i> <%=activity.location %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <h3>You are not going to any activities</h3>
    <% end %>
  </div>
</div>