config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"
  get '/components', to: 'components#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/dashboard', to: 'pages#dashboard', as: :dashboard

  get '/users/:user_id/chat', to: 'chatrooms#new_chatroom_with_user', as: 'new_chatroom_with_user'


  resources :activities do
    collection do
      get :map
    end
    resources :bookings, :comments, only: [:create, :destroy]
  end

  resources :bookings, only: :destroy do
    member do
      get :confirmation
    end
  end

  resources :users, only: :show

  resources :chatrooms, only: [:new,:show, :index, :create] do
    resources :messages, only: :create
  end
end

# Path: app/controllers/pages_controller.rb

app/views/shared/_activity_form.html.erb
<div id="activity-form">

  <% if action_name == "new" %>
    <h3 class="title-edit">Create an Activity</h3>
  <% else %>
    <h3 class="title-edit">Update an Activity</h3>
  <% end %>



  <div data-controller="edit-activity">
      <%= simple_form_for @activity, data: { controller: 'flatpickr' } do |f| %>
        <%= f.input :title, label: false, input_html: { class: 'special', placeholder: "Activity title" } %>
        <%= f.input :description, as: :text, label: false, input_html: { placeholder: "Activity description (min 50 characters)...", rows: "5"} %>
        <div class="mb-3" data-controller="address-autocomplete" data-address-autocomplete-location-value='<%=@activity.location%>' data-address-autocomplete-api-key-value=<%= ENV["MAPBOX_API_KEY"] %>>
          <%= f.input :location, label: false,
            input_html: {data: {address_autocomplete_target: "address"}, class: "d-none", placeholder: "Location"}
            %>
          <%= f.input :longitude, label: false,
            input_html: {data: {address_autocomplete_target: "longitude"}, class: "d-none"}
            %>
          <%= f.input :latitude, label: false,
            input_html: {data: {address_autocomplete_target: "latitude"}, class: "d-none"}
            %>
        </div>
        <%= f.input :time, as: :string, label: false, placeholder: "Select your date", input_html: { data: { flatpickr_target: "time" } } %>
        <div class="container" data-controller="photo-preview">
          <%= f.input :photos, as: :file, input_html: {id: 'photo-input', class: "d-none", multiple: true}, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo', class: "form-control", id: "customFile" %>
            <%= image_tag "", width: 150, class: "hidden", data: { photo_preview_target: "preview"}   %>
          <% unless f.object.new_record? %>
            <p>Pictures already uploaded</p>
              <% @activity.photos.each do |photo| %>
                  <%= cl_image_tag photo.key, class: "picture-preview"  %>
              <% end %>
          <% end %>
        </div>
        <%= f.submit class: 'button-rectangle-orange-create' %>
      <% end  %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= link_to activities_path, class: "nav-link" do %>
    <i class="fa-regular fa-map"></i>
    <p class="title-navbar">Explore</p>
  <% end %>
  <%= link_to new_activity_path, class: "nav-link" do %>
    <i class="fa-regular fa-plus"></i>
    <p class="title-navbar">Create</p>
  <% end %>
  <%= link_to chatrooms_path, class: "nav-link" do %>
    <i class="fa-regular fa-message"></i>
    <p class="title-navbar">Chats</p>
  <% end %>
  <%= link_to user_path(current_user), class: "nav-link" do %>
    <i class="fa-regular fa-user"></i>
    <p class="title-navbar">Dashboard</p>
  <% end %>
</div>