config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"
  get '/components', to: 'components#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/dashboard', to: 'pages#dashboard', as: :dashboard

  get '/users/:user_id/chat', to: 'chatrooms#new_chatroom_with_user', as: 'new_chatroom_with_user'


  resources :activities do
    collection do
      get :map
    end
    resources :bookings, :comments, only: [:create, :destroy]
  end

  resources :bookings, only: :destroy do
    member do
      get :confirmation
    end
  end

  resources :users, only: :show

  resources :chatrooms, only: [:new,:show, :index, :create] do
    resources :messages, only: :create
  end
end

# Path: app/controllers/pages_controller.rb

app/models/activity.rb
class Activity < ApplicationRecord
  # belongs_to :owner, class_name: "User", foreign_key: :user_id
  belongs_to :user
  alias_attribute :owner, :user
  has_many_attached :photos
  has_many :bookings, dependent: :destroy
  has_many :attendees, through: :bookings, source: :user
  validates_presence_of :title, :description, :location, :time, :photos
  validates :description, length: { minimum: 50 }
  geocoded_by :location
  # after_validation :geocode, if: :will_save_change_to_location?
  has_many :comments, dependent: :destroy
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      sql_query = "title ILIKE :query OR description ILIKE :query OR location ILIKE :query"
      @activities = Activity.where(sql_query, query: "%#{params[:query]}%").order(time: :asc)
    else
      @activities = Activity.all.order(time: :asc)
    end
    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: "activities/list", locals: {activities: @activities}, formats: [:html] }
    end
  end

  def map
    @activities = Activity.all.order(time: :asc)
    @activity_info = {}
    @activities.geocoded.each do |activity|
      @activity_info[activity.title.gsub(" ", "-")] = {
        center: [ activity.longitude, activity.latitude ],
        zoom: 10
      }
    end 

    @markers = @activities.geocoded.map { |activity|
      { lat: activity.latitude,
        lng: activity.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {activity: activity})
      }
    }

  end

  def show
    @activity = Activity.find(params[:id])
    @comment = Comment.new
    @already_booked = Booking.where(activity: @activity, user: current_user).any?
    @booking = Booking.new
    @activities = Activity.where(id: params[:id])
    @markers = @activities.geocoded.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude
      }
    end
    if @already_booked
      @booking = Booking.find_by(activity: @activity, user: current_user)
    end
  end

  def new
    @activity = Activity.new
    @user = current_user
  end

  def create
    @activity = Activity.new(activity_params)
    @user = current_user
    @activity.user = @user
    if @activity.save
      redirect_to activity_path(@activity)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update

    if @activity.update(activity_params)
        redirect_to activity_path(@activity)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @activity.destroy
    redirect_to activities_path, status: :see_other, alert: "Activity deleted"
  end



  private

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:title, :description, :location, :latitude, :longitude, :time, photos: [])
  end


end

app/views/activities/_info_window.html.erb
<% activity_title = activity.title.gsub(" ", "-") %>
<div data-map-index-target="card" data-lat="<%= activity.latitude %>" data-lng="<%= activity.longitude %>">
  <%= link_to activity_path(activity) do %>
    <div class="details-box" id="<%= activity_title %>">
      <%= cl_image_tag activity.photos.first.key, crop: :fill, class: "card-map-picture" %>
      <div class= "description-map">
        <h6 id="<%= activity_title %>" class= "title"><%= activity.title %></h6>
        <p class="date"><%= activity.time.strftime('%a, %b %e • %R') %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/activities/_list.html.erb
<div data-search-activities-target="list">
  <h4 class="activities-count"><%= @activities.count %> activities</h4>
  <% @activities.each do |activity| %>
    <%= link_to activity do %>
      <div class="card-index">
        <div class="image-heart">
          <%= cl_image_tag activity.photos.first.key, crop: :fill, class: "card-index-picture" %>
          <div class="div-heart">
            <i class="fa-solid fa-heart heart"></i>
          </div>
        </div>

        <div class= "description-index">
          <h5 class= "title"><%= activity.title %></h5>
          <p class= "location-index"><i class="fa-solid fa-location-dot"></i> <%=activity.location%></p>
          <p class="date"><%= activity.time.strftime('%a, %b %e • %R') %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/activities/edit.html.erb
<div>
  <%= render "shared/activity_form" %>
</div>

app/views/activities/index.html.erb
<div id="activities-index" data-controller="search-activities">

  <%= form_with url: activities_path, method: :get, html: {class:
  "search-form", data: {search_activities_target: "form"}} do |f|%>
      <%= f.text_field :query,
        class: "search-term",
        placeholder: "Search an activity or location",
        value: params[:query],
        data: {
          search_activities_target: "input",
          action: "keyup->search-activities#update"}
      %>
  <% end %>

  <%= render "list", activities: @activities %>
  <div class="map_view">
    <%= link_to map_activities_path, class: "button_map_view" do %>
          <i class="fa-solid fa-map-location-dot"></i> Map View
    <% end %>
  </div>
</div>

app/views/activities/map.html.erb
<div class="map_backgr"
  data-controller="map-index"
  data-map-index-markers-value="<%= @markers.to_json %>"
  data-map-index-info-value="<%= @activity_info.to_json %>"
  data-map-index-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
>
  <div data-map-index-target="box" class="box-container">
    <% @activities.each do |activity| %>
      <%= render "info_window", activity: activity %>
    <% end %>
  </div>
</div>
<div class="map_view list_view mt-3">
    <%= link_to activities_path, class: "button-map-view" do %>
          <i class="fa-solid fa-list"></i> List View
    <% end %>
</div>

app/views/activities/new.html.erb
<div>
  <%= render "shared/activity_form" %>
</div>

app/views/activities/show.html.erb
<div id="activities-show">
  <div class= "pictures">
    <%= cl_image_tag @activity.photos.first.key, class: "card-show-picture"%>
    <%= link_to user_path(@activity.user) do %>
      <%= cl_image_tag @activity.user.photo.key, class: "card-index-profile" %>
    <% end %>
  </div>
  <div>
    <div class= "description-index">
      <h3 class="title"><%= @activity.title %></h3>
      <div>
        <p class="date"><%= @activity.time.strftime('%a, %b %e • %R') %></p>
      </div>
      <div class=" d-flex justify-content-between align-items-center mt-2">

       <i
          class="sharing_i fas fa-share-alt"
          data-controller="share-api"
          data-action="click->share-api#share"
          data-share-api-title-value="<%= @activity.title %>"
          data-share-api-url-value="<%= activity_url(@activity) %>"
          data-share-api-description-value="<%= @activity.description %>"
        >
        </i>
      <div class="btn-join">
        <% if @already_booked == true %>
          <%= link_to "Joined!", activity_booking_path(@activity, @booking), data: { turbo_method: :delete }, class: "button-joined" %>
        <% else %>
          <%= link_to "Join", activity_bookings_path(@activity), data: {turbo_method: :post}, class: "button-join ms-auto" %>
        <% end %>
      </div>

      </div>

    </div>
    <div>
      <p class="details">Details</p>
      <p class="description"><%= @activity.description %></p>
    </div>

    <% if @activity.bookings.any? %>
      <div class="participants">
        <div>
          <p class="details">Who's going (<%= @activity.attendees.size %>)</p>
            <% @activity.attendees.each do |attendee| %>
              <%= link_to user_path(attendee), class: "card-index-going" do %>
                <% if attendee.photo.attached? %>
                  <%= cl_image_tag attendee.photo.key, width: 50, height: 50, class: "card-index-going" %>
                <% else %>
                  <%= image_tag "https://res.cloudinary.com/dzjv9xjxw/image/upload/v1593640008/placeholder-profile-picture-973460_1280_ukqjxu.png", width: 50, height: 50, class: "card-index-profile rounded-circle" %>
                <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="mb-2">
      <p class="details mb-0">Location</p>
      <%=@activity.location %>
    </div>
  </div>
  <div class="map"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <% if @activity.user == current_user %>
    <div class="edit_delete">
      <%= link_to "Edit |", edit_activity_path(@activity), class: "link-edit" %>
      <%= link_to "Delete", activity_path(@activity), data: { turbo_method: :delete, confirm: "Are you sure?" }, class: "link-delete" %>
    </div>
  <% end %>
  <p class="mt-4 mb-1">Comments</p>
  <%= simple_form_for [@activity, @comment] do |f| %>
    <div class="form-group">
      <%= f.input :content, label:false, placeholder: "Leave a comment", input_html: {class: 'form-comment'} %>
    </div>
    <%= f.submit 'Submit', class: 'button-submit' %>
  <% end %>
  <% if @activity.comments.any? %>
    <% @activity.comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment %>
    <% end %>
  <% end %>
</div>